### ISSUE TITLE
Export a choco model to XCSP3

### ISSUE THREAD

**Issue by semantoro** [chocoteam/choco-parsers#13]
Hi choco team,

I want to know if there is a way to export my choco 4.5 model to XCSP3 format.

thank you in advance .

**Comment by cprudhom** [comment]
Hi Semantoro,

No, there is no such feature.
One can either import XCSP3 formatted files, MiniZinc ones and JSON ones, or export to JSON format.
However, everything is ready to export to another format, like XCSP3.
If you feel like doing it, you are very welcome :)

Best,
