### ISSUE TITLE
XCSP: Build problem?

### ISSUE THREAD

**Issue by JiiTee** [chocoteam/choco-parsers#14]
I am trying to export a Choco Model to JSON using Choco parsers. (Choco 4.0.6, Choco-parsers 4.0.4)

 However, a dependency (xcsp3) in the pom.xml of choco-parsers cannot be resolved:

		<dependency>
			<groupId>org.choco-solver</groupId>
			<artifactId>choco-parsers</artifactId>
			<version>4.0.4</version>
		</dependency>

Description	Resource	Path	Location	Type
Missing artifact xcsp3:xcsp3:jar:1.0.1-SNAPSHOT	pom.xml	/SpringCaas	line 3	Maven Dependency Problem

I checked the XCSP website, and did not find a direct match. Is there an easy workaround? Or where to find the  xcsp3:xcsp3:jar:1.0.1-SNAPSHOT ?

Thank you!

**Comment by cprudhom** [comment]
Hi,

try to follow the steps in [XCSP3.md](https://github.com/chocoteam/choco-parsers/blob/master/XCSP3.md).
Or, the required file is in : `/src/main/resources/xcsp-lib/`

Best

**Comment by JiiTee** [comment]
Thanks! Problem solved!

**Comment by rtaupe** [comment]
Hi,

I´m having the same problem and XCSP3.md did not help me ...
I want to use the maven dependency as quoted above to use choco-parsers in another project without having to build choco-parsers manually. Is this possible? If yes, how to deal with the xcsp3 dependency?

Thanks

**Comment by cprudhom** [comment]
Sadly, that is not possible.
You will have to post an issue: https://github.com/xcsp3team/XCSP3-Java-Tools
I, personally, campaign for XCSP3 to be on maven for long time now, so I totally follow you on this.

Best

**Comment by rtaupe** [comment]
Done: https://github.com/xcsp3team/XCSP3-Java-Tools/issues/8
Feel free to vote up :)

**Comment by cprudhom** [comment]
Sure, I'll update it soon
